#!/usr/bin/env bash
# Regenerates src/Generated from the pinned hush-hush submodule via
# openapi-generator's PHP template. Idempotent: running this twice against
# the same submodule commit produces a byte-identical tree. See design.md's
# "Generated/hand-written boundary" and "Spec pinning via git submodule"
# decisions.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

GENERATOR_IMAGE="openapitools/openapi-generator-cli@sha256:2ab0a9680222de65dc9d3baf861aa02b99e1b80c211d8221ebf3ae8f8a102524"
SPEC_COMMIT=$(git -C hush-hush rev-parse HEAD)

rm -rf src/Generated

docker run --rm -u "$(id -u):$(id -g)" \
  -v "$(pwd):/local" \
  "$GENERATOR_IMAGE" generate \
  -i /local/hush-hush/api/openapi.yaml \
  -g php \
  -o /local/src/Generated \
  --invoker-package 'HushHush\Generated' \
  --additional-properties=srcBasePath=,hideGenerationTimestamp=true \
  --global-property models,apis,supportingFiles=ObjectSerializer.php:ApiException.php:Configuration.php:HeaderSelector.php:ModelInterface.php,modelTests=false,apiTests=false,modelDocs=false,apiDocs=false

rm -rf src/Generated/.openapi-generator

# openapi-generator has no custom-code region and doesn't stamp a
# DO-NOT-EDIT header on the PHP template's output — prepend one to every
# generated file, plus the pinned spec commit for spec-version
# traceability, matching the other three SDKs' generated/hand-written
# boundary.
find src/Generated -name '*.php' -print0 | while IFS= read -r -d '' file; do
  awk -v commit="$SPEC_COMMIT" '
    NR == 1 && /^<\?php$/ {
      print
      print "/**"
      print " * Code generated by openapi-generator; DO NOT EDIT."
      print " * Generated from hush-hush spec commit " commit "."
      print " */"
      next
    }
    { print }
  ' "$file" > "$file.tmp"
  mv "$file.tmp" "$file"
done
